daily_orders:
  default_args:
    start_date: 2025-01-01
    retries: 1
  schedule_interval: '@daily'
  catchup: false
  tasks:
    extract:
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: echo extract
    load:
      operator: airflow.providers.standard.operators.bash.BashOperator
      bash_command: echo load
      dependencies: [extract]
